### ISSUE TITLE
Get LDOS in physical units

### ISSUE THREAD

**Issue by mahar** [NanoComp/mpb#129]
Hello, 

I am trying to calculate the Local Density of States for a 1D photonic crystal. Is there a tutorial for this? 
Also I need to convert the electric field in SI units. 

The field units should be [E] = [I]/([L]*eps_0*c)=376.73 V/m where [I] is the current. But what value should I put to be consistent with MPB definitions? 

Thank you!

**Comment by stevengj** [comment]
MPB is an eigensolver.  Given any eigenmode E(x), you can multiply it by *any constant* and get another eigenmode solution.  So, you have to choose a normalization before you can talk about units.

For LDOS calculations, typically one normalizes to unit energy as is reviewed in section 4.4.1 of [this review article](https://arxiv.org/abs/1301.5366).   MPB normalizes modes so that ∫ε|E|²=1 where ε is relative permittivity.   For SI units, you probably want the normalization ½∫ε₀ε|E|²=1, which means you would take the E field from MPB and divide it by sqrt(½ε₀).

To do LDOS calculations in MPB, you might see: https://arxiv.org/abs/1711.07993.   However, it might be easier to use the [LDOS feature of Meep](https://meep.readthedocs.io/en/latest/Python_Tutorials/Local_Density_of_States/).
